subscriber_post:
    path:     /subscriber
    defaults: { _controller: AppBundle:Subscriber:post }
    methods:    [POST]

subscriber_get:
    path:     /subscriber/{email}
    defaults: { _controller: AppBundle:Subscriber:get }
    methods:    [GET]

subscriber_put:
    path:     /subscriber/{email}
    defaults: { _controller: AppBundle:Subscriber:put }
    methods:    [PUT]

subscriber_delete:
    path:     /subscriber/{email}
    defaults: { _controller: AppBundle:Subscriber:delete }
    methods:    [DELETE]